### ISSUE TITLE
NodeJS Socket.io Server v^4.1.2 to 3.1 not connecting

### ISSUE THREAD

**Issue by vamman** [uhm0311/SocketIOSharp#11]
Hello,

We have a NodeJS Server running your sample server js code from the project and when we connect a vanilla client to it we see the following:

`Packet decoding failed. 0{"sid":"lmUcXoLUerfxDmQaAAAF","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":20000} : System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at EngineIOSharp.Common.Packet.EngineIOPacket.Decode(Stream Stream, Boolean IsBinary)
EngineIOSharp.Client.Transport.EngineIOPolling : EngineIOSharp.Common.EngineIOException: Transport is not opened. ReadyState : CLOSED`

Is there a specific version of Socket.io on NodeJS that I should be using?

Thanks!

**Comment by mattv8** [comment]
I'm having the same issue. Note the response `0{"sid":"lmUcXoLUerfxDmQaAAAF","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":20000}` is documented here: https://socket.io/docs/v3/troubleshooting-connection-issues/ which is a valid response.
C#.NET version 4.7.2 running latest version of SocketIOSharp

**Comment by ELKABILLA** [comment]
Hi, im having this exact issue connecting to a Socket.IO v4.2.0 Server , before i was connecting against a v4.0 server, something broken maybe?
Tried via HTTPS and HTTP, none of them worked.
You guys founded a workaround ?

Thanks in advanced.

**Comment by mattv8** [comment]
Unfortunately I was never able to find a workaround with @uhm0311's libraries. I was able to get up and running with  [Quobject/SocketIoClientDotNet/](https://github.com/Quobject/SocketIoClientDotNet/) which is a deprecated project but still working great for my needs.
